In [2]:
import os
import pandas as pd
from urllib.parse import urlparse, unquote, parse_qs, urlunparse, urlencode
import re
import numpy as np
from tqdm import tqdm

tqdm.pandas()

chunks_dir = '../../datasets/alexa-top-1m/chunks/enriched'

In [ ]:
chunks = []

for chunk_file_path in os.listdir(chunks_dir):
  chunks.append(pd.read_csv(f'{chunks_dir}/{chunk_file_path}', index_col=0))

df = pd.concat(chunks, ignore_index=True)

df.info()

df.head()

<class 'pandas.DataFrame'>
RangeIndex: 714866 entries, 0 to 714865
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           714866 non-null  str
 1   enriched_url  714866 non-null  str
dtypes: str(2)
memory usage: 197.4 MB

,url,enriched_url
0,https://royal-lab.net/,"{'https://royal-lab.net/about-us/', 'https://r..."
1,https://creepypastafromthecrypt.blogspot.com/,{'https://creepypastafromthecrypt.blogspot.com...
2,https://www.gosnowmass.com/,{'https://www.gosnowmass.com/activity/uphill-s...
3,https://heilsarmee.ch/,{'https://heilsarmee.ch/themen-angebote/obdach...
4,https://cineten.com/,set()

In [ ]:
df['enriched_url'] = df['enriched_url'].progress_apply(eval)

100%|██████████| 714866/714866 [00:28<00:00, 25398.35it/s]

In [116]:
crawled_urls = set().union(*df['enriched_url'])

In [117]:
crawled_urls

{'https://www.ailr.it/bomboniere-solidali/',
 'http://hackeducation.com/2022/03/08/hope',
 'https://theplayground.co.uk/brian-eno-and-beatie-wolfe-transmit-new-album-liminal-into-space/',
 'https://www.cercle-enseignement.com/Primaire/Toute-l-actualite',
 'https://careers.lausd.org/pc/go/Communications-Careers/9596800/',
 'https://dpa-international.com/economics/urn:newsml:dpa.com:20090101:260207-99-414949',
 'https://hondasae.com/entry2/',
 'https://cityofholland.com/261/Public-Safety',
 'https://www.deece.edu.gr/forum/feed.php?mode=forums',
 'https://mantech.co.za/Stock.aspx?Query=PRE+INSULATEDand',
 'https://demland.pl/recenzje-filmowe-dema',
 'https://abc-gid.ru/author/markavtsov-flur25/',
 'https://www.sp.com.pg/our-brands',
 'https://shopmegadj.com/account/login',
 'https://www.fbbva.es/publicaciones/libro-enfermedades-alergicas/',
 'https://www.kitamura-print.com/print/panel/',
 'https://y-eg.jp/category/midokoro/',
 'https://expireddomains.com/domain/rpbo.com/backlink?hash=b25895',
 'https://pornozec.com/najbolji-chantal-danielle-tubes/',
 'https://medgulfconstruction.com/ongoing/',
 'https://anderbot.com/android/geometry-dash/',
 'https://www.corkcoco.ie/en/resident/community/local-enhancement-programme',
 'https://gokulnath.com/#testimonial',
 'https://www.chyxx.com/wiki/1183946.html',
 'https://zitate.net/schlaf-zitate',
 'https://www.acikbilim.com/radyum-kizlari/',
 'https://chodor-projekt.net/strefa_partnera/',
 'https://rusticlume.com/product-category/mirror-console/',
 'https://www.phxrisingfc.com/tickets/partial/',
 'https://bunny.net/optimizer/',
 'https://www.1000ps.de/motorrad-berichte-von-edi-e-163717',
 'https://www.sixt.com.br/aluguel-de-carro/alemanha/munique/munique-estacao-ferroviaria/',
 'https://odessa-life.od.ua/photo-video#youtube-anchor',
 'https://robodacta.com.mx/product-tag/secundaria/',
 'https://www.sherwoodparc.com/activites/paintball/',
 'https://gamedb.info/rules.html',
 'https://www.grandwinecellar.com/search?q=bourbon*&type=product',
 'https://coloriage.info/coloriagemaisonenpaindepices',
 'https://thefunnybeaver.com/30-funny-tattoos-that-are-sure-to-make-you-sm/',
 'https://seidwear.clothing/collections/t-shirts',
 'https://ganpatuniversity.ac.in/about/governors/people',
 'https://www.tre-pa.jus.br/servicos-judiciais/sessoes-de-julgamento',
 'https://www.elferretero.com.mx/Carrito/Buscador.aspx?Busqueda=LOCK',
 'https://www.estrela.com.br/linhas/carrinhos',
 'https://wp2.medanswering.com/transportation-providers/faq-for-transportation-providers/',
 'https://www.amalytics.co/solutions/cloud-analytics',
 'https://tmorph.weebly.com/mage-tier.html',
 'https://www.yesilist.com/kategori/ekoloji/dongusel-ekonomi/',
 'https://www.risktaisaku.com/category/report',
 'https://elmon.cat/gent/televisio/',
 'https://www.planteaenverde.es/#genesis-nav-primary',
 'https://lewandhuey.com/cdn-cgi/l/email-protection',
 'https://www.hankikoira.fi/koiratietoa/koira-kotona/koiran-ulkoilutus',
 'https://ponchikov.net/health/stomatologiya/17-prichiny-vozniknoveniya-kariesa-i-ego-posledstviya.html',
 'https://www.buildyourownracecar.com/book-review-competition-car-suspension/',
 'https://unipiaget-angola.org/upload/temp/mvv_motricidade.pdf',
 'http://www.huya.com/video/u/1680925919',
 'https://carrerasdemontana.com/2026/02/06/merrell-agility-peak-6-mayayo/?share=linkedin',
 'https://skitdolce.jp/item/IZDL_SOEKJ_01.html',
 'https://www.thesecurityblogger.com/over-2000-fake-shopping-sites-spotted-before-cyber-monday/',
 'https://www.atom.com/premium-domains-for-sale/q/tv show recommendation',
 'https://totusoft.com/lostregistration',
 'https://www.stuttcars.com/porsche-model-research/porsche-cayenne-research/porsche-cayenne-1st-gen-research/',
 'https://www.difc.com/whats-on/news/difc-opens-roofline-a-limited-time-rooftop-destination-for-homegrown-dining-and-culture-concepts',
 'https://www.tabletable.co.uk/en-gb/contact-us',
 'https://www.woodworkerssource.com/self-serve-lumber.html',
 'https://www.localvictory.com/newsletter',
 'https://www.hendrix.edu/visit',
 'https://petlives.jp/letter-cat/2588',
 'https://olen.com/residential/?state=CA',
 'https://www.langenscheidt.com/shop/deutsch/humor-und-unterhaltung-dialekte/',
 'https://www.hypermobility.org/hmsa-education-model',
 'https://deiwos.org/daftar-slot-gacor-hari-ini-dengan-rtp-live-tertinggi-dari-provider-populer/',
 'https://beh.sk/poradna/osem-druhov-zeleniny-na-budovanie-svalov-na-zvysenie-vasej-sily/',
 'https://calcoastnews.com/2025/12/san-luis-obispo-county-deals-on-dining-lodging-happy-hours-7/',
 'https://www.mycenacave.com/lore/story/4',
 'https://bee-realestate.gr/property?id=8cd60eaa-00ec-4d9e-9594-5f840bd72e98',
 'https://www.francefootball.fr/magazine/',
 'https://weare.de/windsurfen',
 'https://www.umtownship.org/calendar.aspx?view=list&year=2026&month=2&day=18&CID=14',
 'https://www.vectorizados.com/vector/22225_ninos-cantando-villancicos/',
 'https://www.electronicsweekly.com/news/business/5ton-evtol-2026-02/',
 'https://keepschool.com/formations/langues-etrangeres/russe/',
 'http://dspt.info/#start_here',
 'http://www.maple-films.com/jrr-tolkiens-the-hobbit.html',
 'https://www.rojsa.com',
 'http://fceobudu.edu.ng/',
 'https://jeanstore.co.uk/collections/hemen-biarritz-underwear/Mens-Hemen-Biarritz-Underwear',
 'https://bk-sagasa-nt.com/tokyo/properties/7150',
 'https://streema.com/about/',
 'https://www.ineventos.com/pa/',
 'https://www.moto-auc.com/bike?pi=24',
 'https://dbgays.com/categories/Straight%2520vs%2520Gay',
 'https://www.algebraclass.ru/category/algebraicheskie-drobi/',
 'https://leon.tecnm.mx/2026/01/13/tecnoticia-008/',
 'https://michelf.ca/accueil/',
 'https://www.waffen-centrale.de/l/cookiepolicy',
 'https://poshe.ir/group/441/%D9%85%D8%B9%D9%85%D8%A7%D8%B1%DB%8C',
 'https://reallove.com/conference-calls/',
 'https://callhub.io/platform/distributed-organizing-sub-accounts/',
 'https://www.swagroup.com/',
 'https://www.inshoes.gr/gynaikeia-papoutsia-inshoes-design',
 'https://www.fonction-publique.gouv.fr/toutes-les-actualites/un-parcours-de-formation-la-transition-ecologique-pour-les-agents-de-letat',
 'http://www.mojkvadrat.rs/kreditni_kalkulator',
 'https://www.fingerpaint.com/#leadership',
 'https://abbathemuseum.com/exhibitions',
 'https://www.magshop.com.au/Products/CategoryCenter/MAMGWK/weekly-magazines-subscription',
 'https://highlark.com/?s=nike',
 'https://honda.com.pe/#productos',
 'https://www.photographersedit.com/#main',
 'https://www.picture-power.com/contact-us.html',
 'https://www.infosec.gov.hk/en/index.php?section=calendar',
 'https://turistickyatlas.cz/registrace',
 'https://www.fiddlehangout.com/store/',
 'https://labadr.com.ua/store/ognetushiteli/',
 'https://qia.qa/en/About/Pages/History.aspx',
 'https://mxplayerdownload.co/mx-player-for-pc-download/',
 'https://www.eng-tips.com/forums/storm-flood-engineering.162/',
 'https://www.omoda.nl/heren/mocassins/',
 'https://rabotainternet.com/kak-najti-nadezhnogo-advokata-v-ispanii-prakticheskij-gid.html',
 'https://lofi45.com/artist/retza/',
 'https://kidcars.tv/modified-power-wheels/',
 'https://theabcshow.com/#schedule',
 'https://www.svetmobilne.cz/recenze/',
 'https://byeon.com',
 'https://addroid.ru/collection/zaschitnye-plenki-dlya-smartfonov-digma',
 'https://www.lettres-utiles.com/articles/les-references-a-indiquer-dans-votre-courrier-2.html',
 'https://www.angelgals.com/search?search=nancy+ajram',
 'https://www.huaxteca.com/porque-huaxteca/',
 'https://sambra.biz/how-to-join-sambra/',
 'https://www.606club.co.uk/visiting-the-606-club-frequently-asked-questions-faqs/',
 'https://malulani.info/?mode=cate&cbid=1454019&csid=0&sort=n',
 'https://memo.co.id/tag/rusia/',
 'https://vahabonline.ir/statics/services/whmcs-setup-security-config/',
 'https://www.pastors.com/contact-us',
 'https://haidangplaza.com.vn/japanese-c11',
 'https://gb.snooper.eu/collections/satellite-navigation-systems',
 'https://www.coveainsurancehub.co.uk/guides',
 'https://irp5.co.za/faq/',
 'https://smarttraffic.blogsky.com/1395/10/12/post-17/%d8%a7%d8%b3%d8%aa%d8%ae%d8%b1%d8%a7%d8%ac-%d8%a8%db%8c%d9%86-%da%a9%d9%88%db%8c%d9%86-%d9%88-%d8%a2%d9%84%d8%aa-%da%a9%d9%88%db%8c%db%8c%d9%86-%d9%87%d8%a7#comments',
 'https://easygym.co.uk/',
 'https://www.goodhousekeeping.com/uk/fit-enough-club/',
 'https://www.sthelens.london/about/work-for-us/',
 'https://irmug.com/forum/#start_here',
 'https://www.theconjugator.com/frnewslesite.php',
 'https://www.gamesville.com/games-at-work',
 'https://www.gildanapoli.it/wp-content/uploads/2020/02/regolamento.pdf',
 'https://hmaauktioner.dk/auction/965',
 'https://www.hosthorde.com/plans/?id=1&price=monthly',
 'https://clarionproject.org/category/alt-right-extremism/patriot-front/',
 'https://theijoem.com/sante',
 'https://smallpondscience.com/tag/fairness/',
 'https://www.der-ersatzteile-profi.de/autoteile/kuehlung/wasserkuehlung/wasserkuehler',
 'https://hipparis.com/category/mom/',
 'https://dollarsprout.com/category/side-gigs-and-hustles/side-hustle-news/',
 'https://www.photoweb.fr/calendrier-photo/calendrier-en-promo',
 'https://indexcall.com/',
 'https://www.indooroopillyshopping.com.au/visit/faqs.html',
 'https://www.assineglobo.com.br/institucional/contratoassinatura',
 'https://miyotamovement.com/brand/#a-why',
 'https://www.festivaldemerida.es/pt/',
 'https://shineon.co.nz/collections/necklaces',
 'https://stroika-arenda.ru/arenda/svarochnye-apparaty',
 'https://www.buesum.de/buesum-erleben/fuehrungen',
 'https://www.kornit.com/ja/',
 'https://nkteh.ru/catalog/markdown/morozilnyy-lar/',
 'https://www.lensway.dk/kontaktlinser/linseliste?p_brandFamily=everclear#clearFilters',
 'https://www.zdnet.com/article/ai-makes-coding-skills-more-important/',
 'https://siripornstar.com/',
 'https://poulailler-bio.fr/rechauffement-climatique-impact-sur-l-elevage-de-poules/',
 'https://www.geomancy.net/forums/store/product/2-2016-flying-stars-using-an-ordinary-compass-book-1-1st-edition/',
 'https://balkanec.bg/spravochnik/add',
 'https://nuorisosaatio.fi/nuorisosaeaetioe/',
 'https://www.cbc.com.br/politica-de-privacidade/',
 'https://smartbid.co/features-subcontractor-management-online',
 'https://moskva.kredity-tut.ru/zaymy?from=vse-o-kreditach.ru#footer',
 'https://ccdm.or.kr/policy.html',
 'https://h2oforyou.co.uk/collections/all',
 'https://www.fransizcasozluk.net/ceviri.html',
 'https://www.magnumpartners.com/privacy-policy',
 'https://politicalopinions.net/americans-hate-trumps-guts/',
 'https://shahr.ir/news/77406/%D8%AC%D9%84%D8%B3%D9%87-%D8%B3%D8%AA%D8%A7%D8%AF-%D9%85%D8%AF%DB%8C%D8%B1%DB%8C%D8%AA-%D8%A8%D8%AD%D8%B1%D8%A7%D9%86-%D8%AA%D9%87%D8%B1%D8%A7%D9%86-%D8%A8%D8%B1%DA%AF%D8%B2%D8%A7%D8%B1-%D8%B4%D8%AF',
 'https://www.kulturechronik.fr/blog/?tag=Actu+Montres+connect%C3%A9es',
 'https://www.pharmaceuticalpress.com/contact/support-and-general-enquiries/',
 'https://www.electronic-star.ro/Pentru-casa/Mobilier/Mese-si-masute/Mese-dining-oxid/',
 'https://putereaplantelor.ro/collections/anemie-copii-239105',
 'https://reset-shop.ru/products?keyword=gl552',
 'https://workflow-automation.podio.com:443/plans.php',
 'https://whalewatch.com/aboutus/professional-affiliations/',
 'https://inforeuma.com/categoria/noticias/noticias-profesionales/',
 'https://www.hondaoflosangeles.com/honda-collision-center-los-angeles-ca-dtw',
 'https://iwanttobeavoiceactor.com/what-we-do/',
 'https://www.becaneweb.net/sonorisation_carte_voeux_flash/',
 'https://superliga168pion.com/contact-us',
 'https://ford.sk/financovanie/moznosti-financovania',
 'https://info.nbin.ca/tips-tools/income-calculator.html',
 'https://plodorodie.ru/t/?tag=%D0%98%D0%B7%D0%B8%D0%B4%D1%80%D0%B8',
 'https://gaski.gov.tr/hizmet-araclarimiz/',
 'https://www.ogvo.nl/blariacumcollege/oog/',
 'https://www.cases.com/pixel-7a-cases/',
 'https://www.elipse.com.br/en/solucao/mobilidade-de-dados-de-tempo-real/',
 'https://ginza-sembikiya.jp/c/premium/assorted_sweets/PGS-512',
 'https://mhsrv.com/diesel-pusher-rvs/',
 'https://www.talagostar.com/product-category/kkodromotor/',
 'https://www.zipline.io/industries/healthcare-hospitals',
 'https://www.platan.ru/company/pek.html',
 'https://www.gplvault.com/product-category/wordpress-plugins/supportcandy/',
 'https://asabe.org/careers/order-of-the-engineer',
 'https://www.clubvwtiguan.com/forums/precios-plazos-de-entrega-y-proceso-de-compra.46/',
 'https://www.americanforce.com/sales/guest/form/',
 'https://flavorite.net/page/2/',
 'https://www.officesupply.com/furniture/c200000.html',
 'https://www.theoaklandpress.com/2026/02/06/a-decades-old-michigan-legal-practice-is-improper-but-murder-other-convictions-will-stand/',
 'https://adwaalwatan.com/category/%d8%a7%d8%ae%d8%a8%d8%a7%d8%b1-%d9%85%d8%aa%d9%86%d9%88%d8%b9%d9%87/',
 'https://vichivisam.ru/?p=50431',
 'https://www.energie-fachberater.de/heizung-lueftung/lueftung-klima/lueftung/',
 'https://gajimu.com/pekerjaan-yanglayak/perlakuan-adil-saat-bekerja/Adil%20di%20Tempat%20Kerja',
 'https://mietdeinobjektiv.de/produkt-kategorie/objektive/sony/zeiss-e-mount/',
 'https://oldripvanwinkle.com/terms-conditions/',
 'https://harnosand.se/e-tjanster-och-blanketter/utbildning-och-forskola/schoolity/schoolity---en-larplattform-for-alla-skolformer.html',
 'https://persianblackberry.ir/2026/02/07/lda-lda-transfer-learning/',
 'https://indianforester.co.in/index.php/indianforester',
 'https://www.seamwork.com/pdf-sewing-patterns',
 'https://espacojuridico.com/espaco-virtual',
 'https://stapravda.ru/circus',
 'https://smriti.com/hindi-songs/see-also/#comments',
 'https://www.beirutnightlife.com/feed/',
 'https://www.dailyfaceoff.com/teams/st-louis-blues/line-combinations',
 'https://filmgrimoire.com/legal/ip',
 'https://www.chem-agilent.com/contents.php?id=1006618',
 'https://mycima-jo.com/genres/27/horror',
 'https://amrod.co.za/catalogue/corporate-gifts?min-price=0&max-price=0&minimum-stock=0&brands=GP&sort-by=PLH&show-count=12&page=1',
 'https://abletunes.com/cart',
 'https://www.haggai-international.org/statement-of-faith/',
 'https://ph0en1x.net/17-domains-and-hosting/',
 'https://cultofbits.com/devicem-pt',
 'https://ledgernote.com/reviews/best-studio-headphones/',
 'https://www.nobuhotels.com/',
 'https://jang.com.pk/news/1554455',
 'https://all4soul.com/vstrechajte-dvulikaya-koshka-chi-roditeli-svalilis-v-chany-s-raznoj-kraskoj/',
 'https://windows10compatible.com/softaken-rar-recovery',
 'https://www.tamausa-kingdom.net/js_study/',
 'https://kulek9.livejournal.com/3148.html',
 'https://www.benzworld.org/showcase/',
 'https://humanlibrary.org/?page_id=7',
 'https://www.motor.com.co/seccion/lanzamientos/probamos-la-pick-hibrida-byd-shark-imponente-ruda-y-poderosa_21182',
 'https://www.solomon.com.tw/corporate_governance/',
 'https://www.smurfitschool.ie/currentstudents/',
 'https://www.hunterdouglas.ca/ethics-compliance',
 'https://ens.dk/energikilder',
 'https://www.heinerfest.de/das-heinerfest/grusswort-ministerpraesident-boris-rhein/',
 'https://www.wilkhahn.com/en/products/task-chairs-office-chairs/',
 'https://www.slu.se/utbildning/studera/kompetensutveckling/meny/kurser/kompetensbevis-for-hasttransportorer/',
 'https://www.thuedp.com/ebab/3mn5goegbw.html',
 'https://www.kp-scalresearch.org/rethinking-ms-treatment-why-less-may-be-more/',
 'https://www.homewardlegal.co.uk/about-us/charging-information',
 'http://neformat.co.ua/index.php?nma=news&fla=stat&nums=42581',
 'http://hatchman.org/ramen-kodawariramenwakatora/',
 'https://bfootball.com.ua/video/',
 'https://www.thehoopsgeek.com/tools/',
 'https://www.matthewhipkin.co.uk/codelib/random-name-generator/',
 'https://crunchybagel.com/migrating-widget-configurations-to-use-appintent/',
 'https://unicode-to-chanakya.blogspot.com/2016/04/plain-text-html-text-var-sccid.html#comment-form',
 'https://www.sr500.de/index.php?user/9022-t-au/',
 'https://uk.aquasphereswim.com/collections/swimwear-new-arrivals',
 'https://www.soccerway.com/burundi/',
 'https://americansuppressorassociation.com/about/asa-dealer-locator',
 'https://vector-park.jp/atm_win.html',
 'https://www.heals.com/lighting/bulbs-and-fittings.html',
 'https://jamestherapy.com/contact/#basiclayout',
 'https://utforskasinnet.se/7-situationer-dar-du-verkligen-lar-kanna-nagon/',
 'https://dolly.com/partners',
 'https://www.membrain.com/challenges/low-win-rates?hsLang=en',
 'https://www.applicantpro.com/pricing',
 'https://wordpress.com/ja/about/',
 'https://www.nost100.com/index.php/wow-private-servers/',
 'https://www.obinb.com/SonList-491457.html',
 'https://www.raitank.jp/comments/feed',
 'https://electronic-city.in/info/Services.php',
 'https://www.dolcevita.com/pages/re-vita',
 'https://www.strapya.com/collections/airtag',
 'https://ru2.vpopku.org/',
 'https://ruswebs.ru/contacts',
 'https://www.cornicello.com/recent.atom',
 'https://wakanoticias.com/sucesos/indigenas-venezolanos-piden-respuestas-sobre-caso-de-homicidio-de-activista.html',
 'https://orangeamps.com/pages/cookies-notice',
 'https://berlingerhaus.com/sahara-marble-nordic/',
 'http://www.edinburgh123.co.uk/blog/sitemap.html',
 'https://www.jdsports.my/collections/sport-gym-men',
 'https://www.das-radhaus.de/fahrraeder/mountainbikes/ktm',
 'https://www.japansubculture.com/a-case-for-making-japanese-art-weird-again/',
 'https://bigtittytube.com/hardcore/',
 'https://www.aiqs.com.au/expert-witness',
 'https://www.illbruck.com/en-gb/products-systems/innovations/i3-sealing-system/',
 'https://ljse.si/si/cetrtletna-revizija-racunskih-parametrov-indeksov-sbitop-in-sbitr-2194/2194',
 'https://www.rainbowresource.com/bargain-material',
 'https://coinsbolhov.ru/catalog/znachki/goroda/',
 'https://www.citizen.co.za/northern-natal-news/local/news-headlines/vryheid-herald/',
 'https://vivood.com/aviso-legal/',
 'https://www.bizmodel.it/droni-e-accessori-video/fpv-racer/propellers/hqprop-bullnose.html',
 'https://cinepax.com/Browsing/General/GeneralEnquiries',
 'https://kaosgl.org/kunye',
 'https://bonga-cams.ru/',
 'https://www.eurocampings.nl/extra-informatie/cookies/',
 'https://rollcall.com/author/nina-heller/',
 'https://www.taxcalc.com/aboutUs.php',
 'https://www.sawadee.nl/singlereizen/europa/portugal/',
 'https://www.conrad.de/de/marken/netatmo.html',
 'https://footballnsw.com.au/competitions/futsal-premier-league-2/',
 'https://www.porcuatrocuartos.com/florero-con-brik/3775',
 'https://autoreview.ru/articles/reyting-test/hroniki-probega-tychinin',
 'https://snus-outlet.ru/page/66',
 'https://www.launchtech.co.uk/launch-code-reader/',
 'https://incestoporno.com/de/',
 'https://westhamworld.co.uk/category/news/',
 'https://completeseo.com/terms/',
 'https://www.eskana.gr/2025_12_03_archive.html',
 'https://zastava-arms.rs/puskomitraljez-m84-m/',
 'https://www.mojaladja.com/forum/index.php/board,139.0.html?PHPSESSID=4i5hos6mjp2de6os4i19kilpuu',
 'https://lucianmindruta.com/feed/',
 'https://web4link.com/new-365-day-journal-i-am-that-i-am-invites-readers-to-experience-god-in-every-moment/',
 'https://www.worldbank.org/en/programs/global-water-security-sanitation-partnership/priority-themes',
 'https://bigcomicbros.net/comics/89375/',
 'https://www.inkia.fr/marques/samsung.html/',
 'https://juicer.deals/reg-seller/',
 'https://www.danysoft.com/curso-power-bi-y-python-para-la-ciencia-de-datos/',
 'https://laut.de/artists/T',
 'https://plaid.com/products/transactions/',
 'https://giocopulito.it/a-tu-per-tu-con-piero-gros-il-leggendario-pierino-dello-sci-azzurro/',
 'http://art-catalog.ru/artist.php?artist=Zaryanko&id_artist=328',
 'https://smartandsun.com/slot',
 'https://alitravel.de/en/',
 'https://entwickler.de/reader/',
 'https://temptationforfood.com/faq/',
 'https://www.innocentive.com/showcases/technology-innovation-institute/',
 'https://www.galagomusic.com/apprendre-le-piano/',
 'https://www.ofertaman.com/search/label/HP%20Store',
 'https://www.hydrasolutions.it/soluzioni-aziendali/',
 'https://f-mirai.jp/sports/baseball/kirihara',

In [ ]:
domains = set(urlparse(url).netloc for url in crawled_urls)

In [119]:
domains

{'e-bunpou.net',
 'alternative-doctor.com',
 'www.wopc.co.uk',
 'www.cinemagay.it',
 'www.fruugo.dk',
 'mpmb.in',
 'www.rintajouppi.fi',
 'www.rtl-theme.com',
 'www.liwenbianji.cn',
 '1post.jp',
 'www.superecono.com',
 'theclearbrands.com',
 'pokercopilot.com',
 'bottlelogic.com',
 'eng.sectsco.org',
 'modlitba.sk',
 'www.iquesta.com',
 'australianfintech.com.au',
 'www.princegeorge.ca',
 'www.foodiesfeed.com',
 'radioguestlist.com',
 'www.louie.com.br',
 'denovosoftware.com',
 'www.happyfoto.cz',
 'www.radio4u.in',
 'web-ace.jp',
 'afaa.com',
 'dnsomatic.com',
 'www.celoxis.com',
 'petelagi.com',
 'uasemena.com.ua',
 'www.totcar.com',
 'tribunaux-rechtbanken.be',
 'fatemi.ir',
 'www.smartspeechtherapy.com',
 'rafaelcarvalho.tv',
 'mof.gov.bt',
 'www.pakistanjobsbank.com',
 'www.cfpc.ca',
 'www.eligibilis.com',
 'www.gympos.sk',
 'mypage.dpub.jp',
 'www.airgunspares.com',
 'newsturk.ru',
 'cinesunstar.com',
 'mamoszurnalas.lt',
 'csociales.wordpress.com',
 'topjobs.lk',
 'www.rbl.bank.in',
 'www.strattonfinance.com.au',
 'www.tenorshare.com',
 'cottonpatch.com',
 'procvetok.ru',
 'mallofqatar.com.qa',
 'emesa.com',
 'personallife.ru',
 'www.uned-derecho.com',
 'amaz0ns.com',
 'orienta.net',
 'www.thebassbarn.com',
 'pbc.gda.pl',
 'parschemical.com',
 'www.twofour54.com',
 'bok.com.pk',
 'www.theadairgroup.com',
 'epaper.bombaysamachar.com',
 'electronicworldtv.co.uk',
 'www.atlantatoyota.com',
 'esxatos.com',
 'yd.com',
 'introvertdear.com',
 'www.torontoairsoft.com',
 'blam.co.jp',
 'pageshd.com',
 'www.trovit.com.pk',
 'www.gbu.ac.in',
 'nportal.pl',
 'www.tstservicios.com',
 'corponet.com',
 'ewhite.com',
 'medcol.rv.ua',
 'www.hlebdoma.by',
 'tjoy.biz',
 'www.vodafone.pt',
 'www.tanmat.org',
 'oddmolly.com',
 'www.atiramhotels.com',
 'www.vinopack.es',
 'www.e-shop.gr',
 'ccari.res.in',
 'wonect.life',
 'www.viterbonews24.it',
 'seshstation.com',
 'www.hammerandrails.com',
 'www.tempkade.ir',
 'losyork.tv',
 'hgcapital.com',
 'www.incognito.com',
 'bitcoin.freefinancetools.net',
 'www.menet.com.cn',
 'www.ccm3.net',
 'mes.bg',
 'crystalwatersystem.pl',
 'www.nonsteam.cz',
 'www.freegames.com',
 'new-team.org',
 'thegoldlininggirl.com',
 'carpenterkessel.com',
 'www.mediaset.es',
 'ijbs.com',
 'startdebatingstophating.com',
 'shufflehound.com',
 'www.idioma.com',
 'www.dolomiti.it',
 'www.skatepro.net',
 'www.bart.aero',
 'www.autonom.ro',
 'kuhnyagid.ru',
 'galka.if.ua',
 'www.momsrising.org',
 'www.bosv.com',
 'www.corsicef.it',
 'www.fastcomet.com',
 'www.ipubliciseafrica.com',
 'www.livefans.jp',
 'logicvapes.co.uk',
 'www.clocktab.com',
 '5cm.ru',
 'www.djuced.com',
 'www.6san.com',
 'araikorea.co.kr',
 'villageofworth.com',
 'kreskowkazone.pl',
 'richrelevance.com',
 'perryssteakhouse.com',
 'http.cat',
 'clusterdesign.org',
 'www.satmarket.com.ua',
 'enterthemeeting.com',
 'modernif.co.kr',
 'targetedvictory.com',
 'www.krasotka-market.ru',
 'www.partirou.com',
 'abcnyheter.no',
 'ipstack.com',
 'varimylo.ru',
 'vfs.edu',
 'www.sergent-major.be',
 'www.pinoyeplans.com',
 'www.livonlabs.com',
 'www.chemionglasses.com',
 'indexq.org',
 'picpaste.de',
 'vesti.kz',
 'baileynelson.com.au',
 'docs.coincap.io',
 'www.grandview.edu',
 'vmax.vn',
 'www.promogim.fr',
 'iq-robot.ru',
 'superheroesrevelados.blogspot.com',
 'www.unexplainable.net',
 'www.seoexpertsindia.com',
 'www.kansasauctions.net',
 'taxcalc.ie',
 'search.com',
 'www.maggiescrochet.com',
 'store-m0o7bk.mybigcommerce.com',
 'global-ssl05.jp',
 'www.cityofpalmdaleca.gov',
 'party-calendar.net',
 'percymeetsarcheage.wordpress.com',
 'www.rohamart.net',
 'www.fishpond.co.nz:443',
 'www.delhievents.com',
 'smartdrive.co.jp',
 'www.grundschulkoenig.de',
 'www.sfj.no',
 'www.psychometrictest.org.uk',
 'www.dot.tk',
 'www.famous-supply.com',
 'www.osx86.net',
 'iz-dereva-svoimi-rukami.ru',
 'www.planetaexcel.ru',
 'www.shirtinator.fr:443',
 'swisstimeclub.ru',
 'www.cordially.jp',
 'onsight.co.uk',
 'www.niedermayer.de',
 'www.mooneyontheatre.com',
 'gjh.sk',
 'weblogma.com',
 'www.curemd.com',
 'www.ycat.co.jp',
 'poderato.com',
 'extramotor.com',
 'www.shinjuku-sportscenter.com',
 'www.biz-samurai.com',
 'www.coromandel.biz',
 'en.ourpalm.com',
 'www.dims.ne.jp',
 'www.amerigas.com',
 'publicdomainq.net',
 'hotbloodanime.blogspot.com',
 'hike.pl',
 'www.immodefrance.com',
 'fptshop.com.vn',
 'educaguia.com',
 'www.88mv.me',
 'www.ghigocalzature.com',
 'www.nnlm.gov',
 'www.ocrconvert.com',
 'androidtop.org',
 'parfum-klick.de',
 'kfspbguga.ru',
 'www.valute.it:443',
 'www.grahambrown.com',
 'www.asg.nl',
 'technik-consulting.eu',
 'millennium.travel',
 'shimibeton.com',
 '2paclegacy.net',
 'www.dagomedia.it',
 'www.erasedtapes.com',
 'cmchbhopal.com',
 'haggarfoundation.org',
 'www.liquibase.com',
 'www.jmcacademy.edu.au',
 'www.efxkits.com',
 'logolessmxtionpictures.tumblr.com',
 'providers.hellohealth.com',
 'www.traveldoc.aero',
 'www.newslaundry.com',
 'spectrumstore.com',
 'www.k-line.fr',
 'ashleighmoneysaver.co.uk',
 'www.geoengineer.org',
 'www.visunext.co.uk:443',
 'whocellphones.com',
 'www.eluxury.com',
 'castellarvalles.cat',
 'www.video-igrice.com',
 'www.ancon.co.uk',
 'optra-india.com',
 'mostlymorgan.com',
 'www.riverbed.com',
 'cyclonesp.blogspot.com',
 'www.dessertnowdinnerlater.com',
 'tecnohotelnews.com',
 'bigfangroup.org',
 'pornasiantube.com',
 'trickoftreat.wordpress.com',
 'sportsland-sugo.co.jp',
 'pornobanya.net',
 'www.sclabs.com',
 'www.vest-news.ru',
 'antidiary.com',
 'www.e-consulters.com.br',
 'dsa.gr',
 'www.fiat.fr',
 'truckersmpstatus.com',
 'soloteenpics.com',
 'portal-preobrazenie.ru',
 'teenfidelityfree.com',
 'xtratuf.com',
 'www.qcharity.org',
 'www.englishclub.com',
 'novavisioninc.com',
 'inventhelp.com',
 'haxe.mazurok.com',
 'www.bjjee.com',
 'www.tanga.com:443',
 'www.bitsoftware.eu',
 'www.ekomi.it',
 'www.webkaise.com',
 'www.thevictoriancosmeticinstitute.com.au',
 'kobietydokodu.pl',
 'www.gazetapolska.pl',
 'www.xjuggler.de',
 'junkiemonkeys.com',
 'www.vieusseux.it',
 'www.justinjohnsonlive.com',
 'www.taftc.org',
 'www.vospsychologues.com',
 'telecomstechacademy.com',
 'fkunissula.ac.id',
 'www.depechedekabylie.com',
 'dazzystore.com',
 'www.clarkpest.com',
 'thealmostdone.com',
 'irantomalaysia.com',
 'madridferias.forogratis.es',
 'www.nausicaa.fr',
 'radonezh.ru',
 'bianji.mobanma.com',
 'www.telefon-treff.de',
 'www.bonitrust.de',
 'www.robertsoncollege.com',
 'wannyan12.com',
 'mothakirat-takharoj.com',
 'hugoribeiro.com.br',
 'www.prolific.com.tw',
 'www.lesimprimantes3d.fr',
 'www.texwipe.com',
 'gazontech.ru',
 'www.pleinair.it',
 'www.kalimbamagic.com',
 'www.needlesports.com',
 'wowubuntu.com',
 'dte.ir',
 'www.pastoralcareinc.com',
 'cerebrodigital.net',
 'monday.com',
 'interaffairs.ru',
 'hibid.com',
 'gamersapparel.co.uk',
 'www.cityofnorthlasvegas.com',
 'hanauta18.com',
 'codepostal.net',
 'www.vwfs.com.br',
 'taka-oneokrock.tumblr.com',
 'www.local10.com:443',
 'superstats.dk',
 'play.mdundo.com',
 'wasatchweatherweenies.blogspot.com',
 'nahrainuniv.edu.iq',
 'cgvi.jp',
 'www.path2college529.com',
 'www.buerklin.com',
 'www.sml.com',
 'supereleman.com',
 'surinaamseradio.com',
 'travel.alot.com',
 'randomprofile.com',
 'reydelparlay.com',
 'upsskirt.ru',
 'truth24.net',
 'dzerkalo.media',
 'beautytips4her.com',
 'www.aikatsu.com',
 'www.miyakou.co.jp',
 'leahcleary.com',
 'yosemite.org',
 'www.la-maison-naturelle.com',
 'thememetro.com',
 'www.shopwang.net',
 'findpenguins.com',
 'se.leplandiscret.com',
 'sjdowntown.com',
 'www.columbiasportswear.de',
 'kurortinfo.ru',
 'www.campus-astrologia.es',
 'naprzod-skalbmierz.futbolowo.pl',
 'www.cmc.com',
 'ieeg.mx',
 'www.oryx-rent.hr',
 'www.norfolkacademy.org',
 'www.lojasrede.com.br',
 'skifska-etnika.com',
 'meny.dk',
 'www.tracksmith.com',
 'makita.one',
 'www.ihalla.com',
 'primaryandsecondary.com',
 'www.transparent.com',
 'poiski-people.ru',
 'www.touring.be',
 'www.torontozoo.com',
 'en.datocapital.com',
 'www.search-for-it.com',
 'shortfilm.com',
 'inn.org',
 'www.miele.dk',
 '3jenan.com',
 'bcmch.org',
 'prof-filter.ru',
 'www.museotamayo.org',
 'sys-guard.com',
 'puzzing.ru',
 'systemarquitectura.com',
 'www.compredia.eu',
 'www.ijsrm.net',
 'calyxinstitute.org',
 'kaigaimm.com',
 'monelitegame.wordpress.com',
 'www.emptymirrorbooks.com',
 '1tac.com',
 'mpopenker.livejournal.com',
 'www.kalinka-realty.ru',
 'www.baania.com',
 'www.lovebikes.pl',
 'www.mantripping.com',
 'www.rockwelltools.com',
 'www.headmasters.com',
 'adverup.com',
 'libertas.mk',
 'biva.jp',
 'www.portico.com',
 'campfire.co.jp',
 'metart.bz',
 'www.tihie.com',
 'www.allezpaillade.com',
 'nationaldailyng.com',
 'globalmuslim.web.id',
 'www.elk101.com',
 'ostapovo-adm.ru',
 'www.remooptimizer.com',
 'www.condorsoaring.com',
 'fellers.com',
 'www.papadatoshome.gr',
 'myseatime.com',
 'www.payzen.eu',
 'www.themostperfectview.com',
 'collegemarching.com',
 'www.dealnews.com:443',
 'theallapps.com',
 'historiasztuki.com.pl',
 'play.verajohn.com',
 'auctionoperation.co.za',
 '1win-kg.casino',
 '213.sk',
 'tangotravel.com.ua',
 'moneyflow.annasavchenkova.ru',
 'www.digitalpayment.net',
 'gunsys.com',
 'eunetworks.com',
 'www.clubkonnect.com',
 'www.city-academy.com',
 'www.lightseekers.cards',
 'www.proanabolics.com',
 'nyugatifeny.hu',
 'www.collonil.com',
 'autobann.su',
 'forum.ucoz.com',
 'www.vbsdn.de',
 'www.nexbelt.com',
 'epmundo.com',
 'rainforestadventure.com',
 'inovum.nl',
 'entertainment.ie',
 'vtfarsi.ir',
 'trainzup.com',
 'zlataky.cz',
 'www.interaction-design.org',
 'www.therxreview.com',
 'www.q-park.de',
 'www.kett.co.jp',
 'spbvedomosti.ru',
 'www.filmcomment.com',
 '2nitki.ru',
 'www.freekoreanfont.com',
 'www.linzi.com',
 'poltekkes-pontianak.ac.id',
 'goodoboi.ru',
 'narkive.com',
 'spwiki.net',
 'www.jikiden.co.jp',
 'rasa.com',
 'seperac.com',
 'www.pcfm.co.ls',
 'titanic-confessions.tumblr.com',
 'www.gemselect.com',
 'www.topcrochetpatterns.com',
 'esigaram.us',
 'cache-kirov.ru',
 'www.transip.nl',
 'www.ifolor.de',
 'www.todaykorea.co.kr',
 'daily-bbw-porn.com',
 'ceskamincovna.cz',
 'conti-tyres.co.uk',
 'masoncityschools.org',
 'www.mini.com.mx',
 'www.tourismlaos.org',
 'philologos.narod.ru',
 '1923.ro',
 'sinohytec.com',
 'www.ccf.org.ph',
 'clickrent.es',
 'pravozem.ru',
 'praacticalaac.org',
 'canarysantabarbara.com',
 'crowdbank.jp',
 'jdcoem.ac.in',
 'murrayresources.com',
 'time.gov',
 'tebfaraz.com',
 'informaimpresa.it',
 'itvplus.net',
 'www.bookschina.com',
 'www.widerspruch.org',
 'www.aitacos.com',
 'ohrid1.com',
 'marcaempleo.es',
 'getmenustar.com',
 'trawickinternational.com',
 'www.stada.es',
 'upy.ac.id',
 'www.toute-la-franchise.com',
 'www.activeactivities.com.au',
 'www.levelblue.com',
 'mainichi.jp',
 'drakortv.com',
 'www.nsk-dental.com',
 'willistower.com',
 'www.fruitfulenglish.com',
 'news.bvf.ru',
 'xcatliu.com',
 'eventsinfocus.org',
 'www.chesshistory.com',
 'bshop-inc.com',
 'www.okeiko-simplelife.com',
 'client.gennassy.com',
 'jurkom74.ru',
 'samvirke.dk',
 'emrecetinblog.com',
 'russianlanguag.swing-zone.com',
 'ptit.edu.vn',
 'www.famigliacecchi.it',
 'masterherald.com',
 'yeumoitruong.vn',
 'netminusa.ru',
 'portuguesvestibular.blogspot.com',
 'www.rentsfnow.com',
 'www.666forum.com',
 'www.biblia.es',
 'p-kin.net',
 'goashlandeagles.com',
 'happyreport.co.kr',
 'k-lite-codec-pack.org.ua',
 'www.manocreditinfo.lt',
 'spritted.com',
 'lant-auto.ru',
 'steeldoor.org',
 'topera.es',
 'www.dille-kamille.be',
 'kuroko-subs.blogspot.com',
 'zagrosn.com',
 'officelist.com',
 'chatzone.jp',
 'www.visitnorway.fr',
 'dalamislam.com',
 'ariavoss.com',
 'www.firsttender.com',
 'download-drv.com',
 '40tygodni.pl',
 'icarda.org',
 'www.itworkroom.com',
 'newjerseysteelbaron.com',
 'athavannews.com',
 'www.bmieducation.com',
 'www.lesfoodies.com:443',
 'pisukisu.com',
 'akuichansera.tumblr.com',
 'eventus.io',
 'osr.org',
 'www.expatden.com',
 'www.gardenswithwings.com',
 'histoireetcollections.com',
 'missionlocal.org',
 'www.germanplast.com',
 'www.stichpunkt.de',
 'libyaninvestment.com',
 'www.frontmatec.com',
 'immo2.pro',
 'www.signatureboston.com',
 'www.vrbsaale-unstrut.de',
 'www.renault.com.br:443',
 'www.nicoleonlineshop.com',
 'mohitzist.blog.ir',
 'nida.co.kr',
 'onlinebuffalo.com',
 'www.mcattestscores.com',
 'blueant.com.au',
 'ekstensifikasi423.blogspot.com',
 'foodandtravel.com',
 'traffichoopla.com',
 'issu.at',
 'www.arquitectes.cat',
 'divi-brasil.com.br',
 'christsquare.com',
 'www.rssing.com',
 'garnamama.com',
 'mazhuren.com',
 'jyouhoukun.com',
 'telegramgeeks.com',
 'www.listening247.com',
 'stricken-haekeln.de',
 'www.easternspirit.org',
 'www.scootergalleri.dk',
 'www.addy.co',
 'sos-office.it',
 'uvm.dk',
 'romanticpornfilms.com',
 'www.legalpleadingtemplate.com',
 'www.tjsg-kokoro.com',
 'yourwebapps.com',
 'prosperotree.com',
 'www.additiverse.com',
 'copyright-topics.jp',
 'www.casinoeuro.com:443',
 'www.olay.com',
 'www.qnapclub.it',
 'www.midlifebachelor.com',
 'www.emochila.com',
 'www.tradew.com',
 'www.benjerry.com',
 'nudebeachdreams.com',
 'www.schoolholidayswa.com.au',
 'cerveceros.org',
 'www.mobilemaya.com',
 'kinoasia.ru',
 'www.plcforum.it',
 'www.tp-link.com',
 'chickenofthesea.com',
 'csaware.com',
 'spellbeeinternational.com',
 'www.greetz.nl',
 'negativo17.org',
 'kapooclubwebboard.net',
 'traders-community.com',
 'www.miad.edu',
 'alkont-maou-sama.blogspot.com',
 'railworks2.ru',
 'wite.ru',
 'www.dialabed.co.za',
 'rt.youporn.com',
 'www.amundocuba.com',
 'vpinball.com',
 'vmeste.eu',
 'xn--42cga5cfx1dle5e0agb2ixai5l6f.com',
 'www.the-aiff.com',
 'www.elitedate.sk',
 'www.hamburg-airport.de',
 'agushkin.ru',
 'www.mcggolf.com',
 'www.inoda-coffee.co.jp',
 'dengfubikes.com',
 'spinifexgroup.com',
 'www.simplyhealthyfamily.org',
 'www.phbern.ch',
 'www.pitchy.fr',
 'www.amando.it',
 'www.around-pune.com',
 'immortaltranslationsblog.wordpress.com',
 'zunko.jp',
 'beebom.com',
 'gofreedownload.net',
 'www.willtheyfit.com',
 'antoines.com',
 'opera.lv',
 'www.idownload.ro',
 'al-o.ru',
 'docs.deployd.com',
 'bestcasinosonline.ng',
 'eera-ecer.de',
 'mangamaniafirenze.it',
 'www.restuner.com',
 'marylandreporter.com',
 'www.itoosoft.com',
 'www.blizzfull.com',
 'vci.ir',
 'www.nbc.ca',
 'remfit.com',
 'rail.1001tur.ru',
 'www.fireflylearning.com',
 'thefootballfreak.com',
 'ribh.wordpress.com',
 'supremofansub.blogspot.com',
 'www.bookstores.com',
 'www.reali.co.il',
 'myphotostyle.org',
 'www.sailboatlistings.com',
 'www.fru.pl',
 'www.soho-tokyo.com',
 'www.dopenzionu.cz',
 'www.semtech.com',
 'lauxanh.org',
 'www.sadasi.com',
 'rgp-journal.ru',
 'liceum36.pl',
 'alkhabeershop.com',
 'www.scutt.eu',
 'www.reliancebankltd.com',
 'www.euromonitor.com',
 'opencaching.pl',
 'junkerhq.net',
 'tsg.metro.tokyo.lg.jp',
 'lynkadoo.com',
 'tokyosmart.jp',
 'benesse-artsite.jp',
 'www.molo.gs',
 'www.foundationforpn.org',
 'parswebserver.com',
 'www.maremagnum.com',
 '7money.co',
 'www.hrl.com',
 'www.fullfabric.com',
 'www.licor.com',
 'latexstories.net',
 'www.klartale.no',
 'limapuluhkotakab.go.id',
 'wwws.airfrance.co.jp',
 'toptour72.ru',
 'www.autogespot.nl',
 'www.adultswim.ca',
 'pdd-helper.ru',
 'ub.life',
 'driversprep.com',
 'www.rgbstock.com',
 'www.meinbobbycar.de',
 'panalangindasaltagalog.blogspot.com',
 'www.clutter.com',
 'www.topformula.se',
 'www.thecandidadiet.com',
 'pointfoundation.org',
 'www.jacksonlewis.com',
 'www.designengineering.com',
 'livingonmyown.pl',
 'www.irdomain.com',
 'mazaninews.ir',
 'shopthemint.com',
 'bluffbakery.com',
 'www.adairhomes.com',
 'topratedmovie.link',
 'www.texjp.org',
 'www.thinkbox.tv',
 'www.hemanual.org',
 'mania.kr',
 'www.puttyandpaint.com',
 'www.intercycles.cl',
 'www.lignanoholiday.com',
 'www.itdix.com',
 'crediton.ge',
 'www.nifdi.org',
 'annauniv.edu',
 'petrosoftinc.com',
 'jobinfo.hu',
 'americantrench.com',
 'esquadraodoconhecimento.wordpress.com',
 'tokio.rs',
 'conversionboosting.com',
 'luatminhgia.com.vn',
 'msugreekplays.org',
 'www.theinvestor.co.kr',
 'www.larepubliquedespyrenees.fr:443',
 'www.mysexshop.co.za',
 'disfruta.la',
 'www.dacia.se:443',
 'www.evolutionnutrition.com',
 'www.templatemark.com',
 'www.ndcs.org.uk',
 'www.orderofgamers.com',
 'www.nordseetourismus.de',
 'www.tsepress.com',
 'mysewingmall.com',
 'biblioklept.org',
 'nycruns.com',
 'washing-machines.ru',
 'www.teaching-materials.org',
 'hwaddress.com',
 'wydr.in',
 'youthvillage.co.za',
 'kudosrecords.co.uk',
 'www.literature-map.com',
 'ekoszalin.pl',
 'www.topquadros.com.br',
 'www.clarke-energy.com',
 'londonreisen.net',
 'sophiamedia.com',
 'ariapix.net',
 'blogantenna.link',
 'doctorfm.ru',
 'delupe.es',
 'naveenpatnaik.com',
 'www.smilinggardener.com',
 'www.flip.kz',
 'www.mercedes-forum.com',
 'homycat.com',
 'bandaancha.eu',
 'www.hardanger-folkeblad.no',
 'www.mrc-academy.org',
 'www.cartracker.ir',
 'laxmedellin.com',
 'crypto-mining.ru',
 'online-converting.com',
 'dragonquest-fan.com',
 'www.tstt.co.tt',
 'www.suzyswede.com',
 'www.poosheshbtj.com',
 'www.wedogood.co',
 'www.loottis.com',
 'www.reiki.org',
 'www.wespa.de',
 'www.segurodirecto.pt',
 'www.ishin-kai.or.jp',
 'www.intergate-immigration.com',
 'www.slidingdoorco.com',
 'fitdir.com',
 'www.ciphr.com',
 'kswiss.com',
 'katolisitas.org',
 'www.mackiteboarding.com',
 'smilebrands.com',
 'www.film.it',
 'cezares-shop.ru',
 'ww2.jeppesen.com',
 'duexpress.in',
 'ultrapro.com',
 'gdfstudio.com',
 'www.provantage.com',
 'theark.org',
 'horror-game.ru',
 'www.ratta.pk',
 'br-linux.org',
 'olagiatingunaika.gr',
 'www.amsterdamuas.com',
 'orhanirmak.com',
 'www.policyexpert.co.uk',
 'stylesalon.com.ua',
 'www.proactiveinvestors.co.uk',
 'www.interlochen.org',
 'www.zudong.com',
 'shate-m.kz',
 'sautomation.eu',
 'www.euronews.com:443',
 'crackzipraronline.com',
 'digitalmindsoft.eu',
 'seafoodfest.org',
 'www.tucervezacasera.com',
 'www.rhythmsnowsports.com.au',
 'www.diy-info.de',
 'allodswiki.ru',
 'www.quersus.com',
 'www.brain.com.tw',
 'amadel37.ru',
 'montenegro-today.com',
 'www.si1230.com',
 'study-in-wroclaw.pl',
 'www.meteoblue.com',
 'www.icelandcarrental.is',
 'www.throughherlookingglass.com',
 'www.unlv.edu',
 'www.ubuy.com.bh',
 'www.spafinder.com',
 'www.innisfreema.com',
 'en.mysexycamera.com',
 'center-clean.de',
 'cccp3d.ru',
 'blogbuster.fr',
 'www.pensamentoverde.com.br',
 'chaumontfs.tmall.com',
 'echourouqmedia.net',
 'www.chong4.com.cn',
 'lyso.vn',
 'www.carolinacrown.org',
 'pahijombang.org',
 'www.upcontent.com',
 'www.pmcu.org',
 'www.imc.ac.at',
 'khantv.pk',
 'gambleonline.us.com',
 'www.e-rewardsmedical.com:443',
 'fezen.hu',
 'guiadeldocente.mx',
 'www.esterbauer.com',
 'unemploymentclaims.org',
 'nativetrailshome.com',
 'altorlocks.com',
 'ddw24.online',
 'broadstage.org',
 'www.snapfitness.com',
 'www.levne-pletivo.cz',
 'www.lightroompresets.com',
 'www.reseliva.com',
 'www.yooopi.at',
 'www.kurs.com',
 'www.nestlecocina.es',
 'visualqa.org',
 'n-afanja.livejournal.com',
 'atlantiscasino.com',
 'fashionel.mk',
 'www.lizardskins.com',
 'www.xue51.com',
 'olivesfordinner.com',
 'elhartista.com',
 'domodi.pl',
 'www.12vi.ru',
 'obligr.com',
 'www.studienscheiss.de',
 'www.vogue.com',
 'meinjob.at',
 'www.gitarren.se',
 'www.montanasegura.com',
 'www.centerdevice.de',
 'silicon.ac.in',
 'pesdb.net',
 'www.tallyknowledge.com',
 'www.thesamayabali.com',
 'www.alquds.edu',
 'www.familiejournal.dk',
 'www.pioneerspost.com',
 'www.itscope.com:443',
 'nabdalsharea.blogspot.com',
 'www.aldineisd.org',
 'www.fetisch.de',
 'www.snowinginhell.com',
 'floydhome.com',
 'www.carburetor-parts.com',
 'hexanova.se',
 'a-denki.co.jp',
 'legionisci.com',
 'mva.nl',
 'www.buzzwoo.de',
 'www.leadpages.com',
 'www.olimpiadadehistoria.com.br',
 'eru.gov.cz',
 'bravo.am',
 'www.poferries.com',
 'tripura.nic.in',
 'humaneconomy.it',
 'www.batamfast.com',
 'www.sexfrancais.net',
 'qifi.org',
 'gorce24.pl',
 'oselhoztehnike.ru',
 'www.msjonline.org',
 'www.vaken.se',
 'ourrevolution.com',
 'www.samstores.com',
 'shafiqolbu.wordpress.com',
 'www.smittybilt.com',

In [121]:
crawled_df = pd.DataFrame({'url': list(crawled_urls)})

In [122]:
df = pd.concat([df[['url']], crawled_df], ignore_index=True)

In [123]:
df

                                                       url
0                                   https://royal-lab.net/
1            https://creepypastafromthecrypt.blogspot.com/
2                              https://www.gosnowmass.com/
3                                   https://heilsarmee.ch/
4                                     https://cineten.com/
...                                                    ...
3485251                      https://csonline2.net/servers
3485252  https://www.aallnet.org/education-training/in-...
3485253        https://www.disney.es/peliculas/toy-story-5
3485254                       https://honari.com/candleCal
3485255           https://morris.gr/schetika-me-ti-morris/

[3485256 rows x 1 columns]

In [124]:
df['url'].nunique()

3231343

In [ ]:
def strip_to_base_url(url):
    """
    Strip URL to just scheme + netloc (e.g., https://example.com/)
    """
    parsed = urlparse(url)
    return urlunparse((
        parsed.scheme,
        parsed.netloc,
        '/',  # Just root path
        '',   # No params
        '',   # No query
        ''    # No fragment
    ))
    
print(
  strip_to_base_url('https://cast-ad.co.jp/works/%e5%8c%bb%e7%99%82%e6%b8%ac%e5%ae%9a%e5%99%a8%e3%81%a8%e9%80%a3%e5%8b%95%e3%81%97%e3%81%9f%e3%82%ab%e3%83%ab%e3%83%86%e3%82%a2%e3%83%97%e3%83%aa%e3%81%ae%e9%96%8b%e7%99%ba%ef%bc%9a%e5%8c%bb%e7%99%82/')
)

https://cast-ad.co.jp/

In [127]:
def strip_params(url):
    """
    Strip URL to just scheme + netloc (e.g., https://example.com/)
    """
    parsed = urlparse(url)
    return urlunparse((
        parsed.scheme,
        parsed.netloc,
        parsed.path,
        '',   # No params
        '',   # No query
        ''    # No fragment
    ))

In [128]:
def remove_specific_params(url, params_to_remove):
    """
    Remove specific query parameters, keep all others
    Does NOT cascade - only removes the exact params specified
    """
    parsed = urlparse(url)
    
    if not parsed.params and not parsed.query:
        return url
    
    params = parse_qs(parsed.params, keep_blank_values=True)
    query = parse_qs(parsed.query, keep_blank_values=True)
    
    # Remove only specified params (case-insensitive)
    clean_params = {
        k: v for k, v in params.items()
        if all(p.lower() not in k.lower()  for p in params_to_remove)
    }
    
    clean_query = {
        k: v for k, v in query.items()
        if all(p.lower() not in k.lower()  for p in params_to_remove)
    }
    
    # Rebuild query
    new_params = urlencode(clean_params, doseq=True) if clean_params else ''

    new_query  = urlencode(clean_query, doseq=True)  if clean_query  else ''
    
    return urlunparse((
        parsed.scheme,
        parsed.netloc,
        parsed.path,
        new_params,
        new_query,
        parsed.fragment
    ))
    
print(
  remove_specific_params(
    'https://chemnetbase.com/search/SimpleSearch.xhtml;jsessionid=FE7D77AC8225B27425FC97DF6097E119?dswid=-5046',
    {'utm_campaign', 'utm_medium', 'utm_source', 'sessionid'}
  )
)

https://chemnetbase.com/search/SimpleSearch.xhtml?dswid=-5046

In [ ]:
# 1. Domain parking/marketplace
parking_services = [
  'hugedomains.com', 'afternic.com', 'sedo.com', 'dropcatch.com',
  'domainmarket.com', 'brandbucket.com', 'expireddomains.com',
  'forsaledomain.net', 'dynadot.com', 'domain_profile.cfm'
]

# Tracking params to remove
TRACKING_PARAMS = {
  # Tracking
  'utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term',
  # Analytics
  'fbclid', 'gclid', '_ga', '_gac', 'mc_cid', 'mc_eid',
  # Session IDs
  'phpsessid', 'jsessionid', 'sessionid', 'sid', 'aspsessionid',
  # OAuth/Auth tokens (for Google accounts specifically)
  'state', 'nonce', 'code', 'client-request-id', 'wsucxt', 'claims',
  'response_type', 'response_mode', 'flowname', 'flowentry', 'passive',
  'ifkv', 'dsh', 'authuser', 'authError', 'client_id', 'continue',
  'followup', 'dsh', 'sv',
  # Misc tokens
  'uuid', 'vid', 'nk', 'client_key', 'cobrandid',
  # Referrals
  'sharename', 'ref', 'source', 'from', 'referrer',
}

def clean_url(url):
  url_lower = url.lower()
  
  parsed = urlparse(url)
  netloc = parsed.netloc.lower()
  url_clean = remove_specific_params(url, TRACKING_PARAMS)

  # sampling 1% of parking urls
  if any(ps in url_lower for ps in parking_services):
    if np.random.random() < 0.01:
      return url_clean
    else:
      return None

  # sampling 1% of tumblr urls
  if 'tumblr.com' in netloc and netloc not in ['www.tumblr.com', 'tumblr.com']:
    if np.random.random() < 0.01:
      return url_clean
    else:
      return None

  # stripping suspend/error/captcha pages to base
  if 'login.microsoftonline.com' in netloc or any(x in parsed.path.lower() for x in ['/suspendedpage', '/404.html', '/page-not-found', '/error']) or  any(x in url_lower for x in ['captcha', 'iamhuman', '/waf/verify', '/validation/', 'bot-check', 'bot_check']):
    if np.random.random() < 0.01:
      return url_clean
    else:
      return strip_to_base_url(url_clean)
  
  # 'accounts.google.com' urls
  if 'accounts.google.com' in netloc:
    return strip_params(url_clean)

  # removing ip addresses, we'll suppose they are all malicious because ip addresses look all the same
  if re.match(r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', netloc):
    return None
  
  unquoted_url = unquote(url_clean)

  while unquoted_url != url_clean:
    url_clean = unquoted_url
    unquoted_url = unquote(url_clean)
    
  return unquoted_url

In [142]:
df['clean_url'] = df['url'].progress_apply(clean_url)

100%|██████████| 3485256/3485256 [01:29<00:00, 39136.13it/s]

In [ ]:
df.drop(df[df['url'].str.len() > 5000].index, inplace=True)
df.reset_index(drop=True, inplace=True)

In [ ]:
# df.loc[df['clean_url'].notna(), ['clean_url']].drop_duplicates(ignore_index=True).rename(columns={'clean_url': 'url'}).to_csv('../../datasets/benign.csv')

In [ ]:
# samples_df = pd.read_csv('../../datasets/benign.csv', index_col=0).sample(frac=0.3, ignore_index=True)

In [ ]:
# samples_df.to_csv('../../datasets/samples.csv')

In [8]:
df = pd.read_csv('../../datasets/benign.csv', index_col=0)

df

                                                       url
0                                    https://royal-lab.net
1             https://creepypastafromthecrypt.blogspot.com
2                               https://www.gosnowmass.com
3                                    https://heilsarmee.ch
4                                      https://cineten.com
...                                                    ...
3179075                      https://csonline2.net/servers
3179076  https://www.aallnet.org/education-training/in-...
3179077        https://www.disney.es/peliculas/toy-story-5
3179078                       https://honari.com/candleCal
3179079            https://morris.gr/schetika-me-ti-morris

[3179080 rows x 1 columns]