In [ ]:
import pandas as pd
import os

chunks_folder = '../../datasets/alexa-top-1m/chunks'
chunks_2nd_attempt_folder = '../../datasets/alexa-top-1m/chunks/2nd_attempt'
chunks_with_vpn_folder = '../../datasets/alexa-top-1m/chunks/2nd_attempt/with_vpn'
chunks = []

for file_path in os.listdir(chunks_folder):
  if file_path.endswith('.csv'):
    chunks.append(pd.read_csv(f'{chunks_folder}/{file_path}', index_col=0))
    
for file_path in os.listdir(chunks_2nd_attempt_folder):
  if file_path.endswith('.csv'):
    chunks.append(pd.read_csv(f'{chunks_2nd_attempt_folder}/{file_path}', index_col=0))
    
for file_path in os.listdir(chunks_with_vpn_folder):
  if file_path.endswith('.csv'):
    chunks.append(pd.read_csv(f'{chunks_with_vpn_folder}/{file_path}', index_col=0))

In [81]:
for chunk in chunks:
  print(chunk.shape)

(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(20000, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(16893, 2)
(15119, 2)
(15119, 2)
(17, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)
(15119, 2)

In [82]:
chunks[0]

                              url                        resolved_url
840000  buenosairescompras.gob.ar  https://buenosairescompras.gob.ar/
840001        furuitang.tmall.com                                 NaN
840002             zhujinwang.com                                 NaN
840003                 aeipro.com                                 NaN
840004            technokarak.com            https://technokarak.com/
...                           ...                                 ...
859995            objetivismo.org                                 NaN
859996         ejawatanonline.com                                 NaN
859997                oneword.com                https://oneword.com/
859998                gauntlet.gg                                 NaN
859999                      nt.az                                 NaN

[20000 rows x 2 columns]

In [83]:
df = pd.concat(chunks, ignore_index=True).sort_values(by='resolved_url').drop_duplicates(subset='url', ignore_index=True)

df.info()
print(df.describe())
df

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 2 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   url           1000000 non-null  str
 1   resolved_url  730147 non-null   str
dtypes: str(2)
memory usage: 48.9 MB
              url                              resolved_url
count     1000000                                    730147
unique    1000000                                    714866
top     0-kms.com  https://store.taobao.com/shop/noshop.htm
freq            1                                       406

                       url       resolved_url
0                0-kms.com  http://0-kms.com/
1                00-000.pl  http://00-000.pl/
2                  0000.jp    http://0000.jp/
3                 000a.biz   http://000a.biz/
4                000pc.net  http://000pc.net/
...                    ...                ...
999995      ignition.co.za                NaN
999996        poporo.ne.jp                NaN
999997  scuolasicurezza.it                NaN
999998          km43yy.com                NaN
999999        cool-boom.ru                NaN

[1000000 rows x 2 columns]

In [84]:
na_mask = df['resolved_url'].isna()

na_mask.sum()

np.int64(269853)

In [85]:
resolved_df = df.loc[~na_mask]

resolved_df

                  url            resolved_url
0           0-kms.com       http://0-kms.com/
1           00-000.pl       http://00-000.pl/
2             0000.jp         http://0000.jp/
3            000a.biz        http://000a.biz/
4           000pc.net       http://000pc.net/
...               ...                     ...
730142      zzzrs.net      https://zzzrs.net/
730143   zzzscore.com   https://zzzscore.com/
730144  zzzsearch.com  https://zzzsearch.com/
730145    zzztube.com    https://zzztube.com/
730146      zzzyk.com      https://zzzyk.com/

[730147 rows x 2 columns]

In [86]:
resolved_df.info()
resolved_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 730147 entries, 0 to 730146
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           730147 non-null  str
 1   resolved_url  730147 non-null  str
dtypes: str(2)
memory usage: 41.1 MB

              url                              resolved_url
count      730147                                    730147
unique     730147                                    714866
top     0-kms.com  https://store.taobao.com/shop/noshop.htm
freq            1                                       406

In [87]:
resolved_df

                  url            resolved_url
0           0-kms.com       http://0-kms.com/
1           00-000.pl       http://00-000.pl/
2             0000.jp         http://0000.jp/
3            000a.biz        http://000a.biz/
4           000pc.net       http://000pc.net/
...               ...                     ...
730142      zzzrs.net      https://zzzrs.net/
730143   zzzscore.com   https://zzzscore.com/
730144  zzzsearch.com  https://zzzsearch.com/
730145    zzztube.com    https://zzztube.com/
730146      zzzyk.com      https://zzzyk.com/

[730147 rows x 2 columns]

In [90]:
resolved_df[['resolved_url']].drop_duplicates(ignore_index=True).rename(columns={'resolved_url': 'url'}).to_csv(f'../../datasets/alexa-top-1m/top-1m-resolved.csv', )